version: '3'
services:
  frontend:
    image: frontendpfa
    ports:
      - "4200:80" 
    networks:
      - frontendNetwork

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pfa2024nadaomri2024%
      MYSQL_DATABASE: base
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - backendNetwork

  backend:
    image: backendpfa
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    #he4i jdida pushi trah
    command: ["sh", "-c", "wait-for-it.sh mysql:3306 -- java -jar /app/backendpfa.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/base?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pfa2024nadaomri2024%
    networks:
      - backendNetwork
      - frontendNetwork

networks:
  backendNetwork:
  frontendNetwork:

volumes:
  mysqldata:
