version: '3'
services:
  frontend:
    image: nadaomri2001/frontendpfa 
    ports:
      - "4200:80" 

  mysql:
    image: nadaomri2001/mysql 
   
    environment:
      MYSQL_ROOT_PASSWORD: pfa2024nadaomri2024%
      MYSQL_DATABASE: base
    volumes:
      - mysqll:/var/lib/mysql
    networks:
      - backendNetwork

  backend:
    image: nadaomri2001/backendpfa 
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    
    command: ["java", "-jar", "/app/backendpfa.jar"]
    networks:
      - backendNetwork
      - frontendNetwork

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/base?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pfa2024nadaomri2024%

networks:
  backendNetwork:
  frontendNetwork:

volumes:
  mysqll: