name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and push frontend Docker image
        run: |
          docker login sitepfa.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker build -t sitepfa.azurecr.io/frontend:${{ github.sha }} ./front
          docker push sitepfa.azurecr.io/frontend:${{ github.sha }}

  build_and_deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and push backend Docker image
        run: |
          docker login sitepfa.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker build -t sitepfa.azurecr.io/backend:${{ github.sha }} ./backend
          docker push sitepfa.azurecr.io/backend:${{ github.sha }}
